name: Czech National Repository UI

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install @quasar/cli yarn
          yarn install
      - name: Lint and test
        run: |
          yarn run lint
          yarn test
  build:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Node version
        run: node --version
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install @quasar/cli yarn
          yarn install
      - name: Build for production
        run: yarn build --if-present
      - name: Set RELEASE_VERSION
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
      - name: Upload production dist artifact
        uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          name: dist-spa-${{ env.RELEASE_VERSION }}
          path: |
            dist
            !dist/**/*.md
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Set RELEASE_VERSION
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
      - uses: actions/download-artifact@v2
        with:
          name: dist-spa-${{ env.RELEASE_VERSION }}
      - name: Publishing distribution
        run: ls -R
      - name: Package SPA distribution asset
        run: tar czvf /tmp/dist-spa-${{ env.RELEASE_VERSION }}.tar.gz spa
      - name: Release SPA distribution asset
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/dist-spa-${{ env.RELEASE_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
